{"kind":"symbol","variants":[{"paths":["\/documentation\/mealziossdk\/mealzfavoritesfeatureuikit\/init(hidetitles:recipedetailsconstructor:favoritesfeatureconstructor:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Initializer","modules":[{"name":"MealziOSSDK"}],"role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"hideTitles","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"favoritesFeatureConstructor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK27FavoritesFeatureConstructorV","text":"FavoritesFeatureConstructor","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[{"introducedAt":"14.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"14.0","name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"14.0","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false}],"title":"init(hideTitles:recipeDetailsConstructor:favoritesFeatureConstructor:)","externalID":"s:11MealziOSSDK26MealzFavoritesFeatureUIKitC10hideTitles24recipeDetailsConstructor09favoriteseK0ACSb_AA06RecipejeK0VAA0deK0Vtcfc"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier"},{"kind":"text","text":" = RecipeDetailsFeatureConstructor(), "},{"text":"favoritesFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FavoritesFeatureConstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/FavoritesFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK27FavoritesFeatureConstructorV"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzFavoritesFeatureUIKit"]]},"sections":[],"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzFavoritesFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:favoritesFeatureConstructor:)","interfaceLanguage":"swift"},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzFavoritesFeatureUIKit/init(hideTitles:recipeDetailsConstructor:favoritesFeatureConstructor:)":{"url":"\/documentation\/mealziossdk\/mealzfavoritesfeatureuikit\/init(hidetitles:recipedetailsconstructor:favoritesfeatureconstructor:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"favoritesFeatureConstructor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK27FavoritesFeatureConstructorV","text":"FavoritesFeatureConstructor"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"title":"init(hideTitles:recipeDetailsConstructor:favoritesFeatureConstructor:)","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzFavoritesFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:favoritesFeatureConstructor:)"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/FavoritesFeatureConstructor":{"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FavoritesFeatureConstructor"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/FavoritesFeatureConstructor","title":"FavoritesFeatureConstructor","url":"\/documentation\/mealziossdk\/favoritesfeatureconstructor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FavoritesFeatureConstructor"}],"abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzFavoritesFeatureUIKit":{"url":"\/documentation\/mealziossdk\/mealzfavoritesfeatureuikit","navigatorTitle":[{"text":"MealzFavoritesFeatureUIKit","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzFavoritesFeatureUIKit"}],"role":"symbol","abstract":[],"title":"MealzFavoritesFeatureUIKit","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzFavoritesFeatureUIKit"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MealzFavoritesFeatureUIKit","op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzFavoritesFeatureUIKit\/title"},{"value":[{"kind":"identifier","text":"MealzFavoritesFeatureUIKit"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzFavoritesFeatureUIKit\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MealzFavoritesFeatureUIKit"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzFavoritesFeatureUIKit\/navigatorTitle"}]}]}