{"variants":[{"paths":["\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/init(recipeid:ismealzrecipe:recipedetailsconstructor:recipecardconstructor:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(recipeId:isMealzRecipe:recipeDetailsConstructor:recipeCardConstructor:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"modules":[{"name":"MealziOSSDK"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"14.0"},{"name":"iPadOS","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false,"deprecated":false}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recipeId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isMealzRecipe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor"},{"text":", ","kind":"text"},{"text":"recipeCardConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"StandaloneRecipeCardConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV"},{"text":")","kind":"text"}],"roleHeading":"Initializer","role":"symbol","title":"init(recipeId:isMealzRecipe:recipeDetailsConstructor:recipeCardConstructor:)","externalID":"s:11MealziOSSDK30MealzStandaloneRecipeCardUIKitC8recipeId02iscE00H18DetailsConstructor0hfL0ACSS_SbAA0ek7FeatureL0VAA0defL0Vtcfc","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"recipeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isMealzRecipe","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor"},{"kind":"text","text":" = RecipeDetailsFeatureConstructor(), "},{"text":"recipeCardConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"StandaloneRecipeCardConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StandaloneRecipeCardConstructor"},{"kind":"text","text":" = StandaloneRecipeCardConstructor())"}]}],"kind":"declarations"}],"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit":{"url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit","abstract":[],"navigatorTitle":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}],"title":"MealzStandaloneRecipeCardUIKit","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit/init(recipeId:isMealzRecipe:recipeDetailsConstructor:recipeCardConstructor:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recipeId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isMealzRecipe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeCardConstructor"},{"text":": ","kind":"text"},{"text":"StandaloneRecipeCardConstructor","preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/init(recipeid:ismealzrecipe:recipedetailsconstructor:recipecardconstructor:)","title":"init(recipeId:isMealzRecipe:recipeDetailsConstructor:recipeCardConstructor:)","abstract":[],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(recipeId:isMealzRecipe:recipeDetailsConstructor:recipeCardConstructor:)","kind":"symbol","role":"symbol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/StandaloneRecipeCardConstructor":{"navigatorTitle":[{"text":"StandaloneRecipeCardConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"StandaloneRecipeCardConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/standalonerecipecardconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StandaloneRecipeCardConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"StandaloneRecipeCardConstructor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/title","value":"MealzStandaloneRecipeCardUIKit"},{"value":[{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}],"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/fragments"},{"op":"replace","value":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/navigatorTitle"}]}]}