{"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(recipe:recipeDetailsConstructor:recipeCardConstructor:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit"]]},"variants":[{"paths":["\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/init(recipe:recipedetailsconstructor:recipecardconstructor:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"recipe","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MealzcoreRecipe","kind":"typeIdentifier","text":"Recipe"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier"},{"kind":"text","text":" = RecipeDetailsFeatureConstructor(), "},{"text":"recipeCardConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"StandaloneRecipeCardConstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StandaloneRecipeCardConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV"},{"text":" = StandaloneRecipeCardConstructor())","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"MealziOSSDK"}],"title":"init(recipe:recipeDetailsConstructor:recipeCardConstructor:)","externalID":"s:11MealziOSSDK30MealzStandaloneRecipeCardUIKitC6recipe0H18DetailsConstructor0hfJ0ACSo09MealzcoreE0C_AA0ei7FeatureJ0VAA0defJ0Vtcfc","symbolKind":"init","platforms":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false,"introducedAt":"14.0"},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"14.0"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"recipe","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MealzcoreRecipe","kind":"typeIdentifier","text":"Recipe"},{"kind":"text","text":", "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeCardConstructor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StandaloneRecipeCardConstructor","preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"kind":"symbol","references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit/init(recipe:recipeDetailsConstructor:recipeCardConstructor:)":{"title":"init(recipe:recipeDetailsConstructor:recipeCardConstructor:)","role":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(recipe:recipeDetailsConstructor:recipeCardConstructor:)","url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/init(recipe:recipedetailsconstructor:recipecardconstructor:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"recipe","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Recipe","preciseIdentifier":"c:objc(cs)MealzcoreRecipe"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor"},{"kind":"text","text":", "},{"text":"recipeCardConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV","text":"StandaloneRecipeCardConstructor"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit":{"url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit","abstract":[],"navigatorTitle":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}],"title":"MealzStandaloneRecipeCardUIKit","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/StandaloneRecipeCardConstructor":{"navigatorTitle":[{"text":"StandaloneRecipeCardConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"StandaloneRecipeCardConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/standalonerecipecardconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StandaloneRecipeCardConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"StandaloneRecipeCardConstructor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/title","value":"MealzStandaloneRecipeCardUIKit"},{"value":[{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/navigatorTitle"}]}]}