{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/init(criteria:recipedetailsconstructor:recipecardconstructor:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"criteria"},{"kind":"text","text":": "},{"text":"SuggestionsCriteria","preciseIdentifier":"c:objc(cs)MealzcoreSuggestionsCriteria","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor"},{"text":" = RecipeDetailsFeatureConstructor(), ","kind":"text"},{"kind":"externalParam","text":"recipeCardConstructor"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StandaloneRecipeCardConstructor","kind":"typeIdentifier","text":"StandaloneRecipeCardConstructor","preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV"},{"kind":"text","text":" = StandaloneRecipeCardConstructor())"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(criteria:recipeDetailsConstructor:recipeCardConstructor:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit"]]},"metadata":{"modules":[{"name":"MealziOSSDK"}],"symbolKind":"init","title":"init(criteria:recipeDetailsConstructor:recipeCardConstructor:)","externalID":"s:11MealziOSSDK30MealzStandaloneRecipeCardUIKitC8criteria24recipeDetailsConstructor0ifK0ACSo28MealzcoreSuggestionsCriteriaC_AA0ej7FeatureK0VAA0defK0Vtcfc","role":"symbol","platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0"},{"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"14.0","unavailable":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"criteria","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MealzcoreSuggestionsCriteria","text":"SuggestionsCriteria","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor"},{"text":", ","kind":"text"},{"text":"recipeCardConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV","text":"StandaloneRecipeCardConstructor","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit/init(criteria:recipeDetailsConstructor:recipeCardConstructor:)":{"url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/init(criteria:recipedetailsconstructor:recipecardconstructor:)","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(criteria:recipeDetailsConstructor:recipeCardConstructor:)","abstract":[],"title":"init(criteria:recipeDetailsConstructor:recipeCardConstructor:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"criteria","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SuggestionsCriteria","preciseIdentifier":"c:objc(cs)MealzcoreSuggestionsCriteria","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"text":", ","kind":"text"},{"text":"recipeCardConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV","text":"StandaloneRecipeCardConstructor","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit":{"url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit","abstract":[],"navigatorTitle":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}],"title":"MealzStandaloneRecipeCardUIKit","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/StandaloneRecipeCardConstructor":{"navigatorTitle":[{"text":"StandaloneRecipeCardConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"StandaloneRecipeCardConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/standalonerecipecardconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StandaloneRecipeCardConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"StandaloneRecipeCardConstructor","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/title","op":"replace","value":"MealzStandaloneRecipeCardUIKit"},{"value":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/navigatorTitle","value":[{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}