{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/viewdidload()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/viewdidload()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"metadata":{"externalID":"c:@M@MealziOSSDK@objc(cs)MealzStandaloneRecipeCardUIKit(im)viewDidLoad","modules":[{"name":"MealziOSSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0"},{"beta":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0"}],"role":"symbol","roleHeading":"Instance Method","title":"viewDidLoad()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}]},"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/viewDidLoad()","interfaceLanguage":"swift"},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit/viewDidLoad()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"type":"topic","url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/viewdidload()","role":"symbol","kind":"symbol","title":"viewDidLoad()","abstract":[],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/viewDidLoad()"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit":{"url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit","abstract":[],"navigatorTitle":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}],"title":"MealzStandaloneRecipeCardUIKit","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"viewDidLoad"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"viewDidLoad","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit~1viewDidLoad()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit~1viewDidLoad()\/fragments"},{"value":"MealzStandaloneRecipeCardUIKit","op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/title"},{"value":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/navigatorTitle","value":[{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}