{"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyMealsFeatureUIKit"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"hideTitles","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"text":", ","kind":"text"},{"text":"myMealsContructor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MyMealsFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK25MyMealsFeatureConstructorV"},{"text":")","kind":"text"}],"symbolKind":"init","title":"init(hideTitles:recipeDetailsConstructor:myMealsContructor:)","role":"symbol","platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0"},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","beta":false}],"roleHeading":"Initializer","externalID":"s:11MealziOSSDK24MealzMyMealsFeatureUIKitC10hideTitles24recipeDetailsConstructor02myE10ContructorACSb_AA06RecipekfL0VAA0defL0Vtcfc","modules":[{"name":"MealziOSSDK"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/mealziossdk\/mealzmymealsfeatureuikit\/init(hidetitles:recipedetailsconstructor:mymealscontructor:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hideTitles"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor"},{"kind":"text","text":" = RecipeDetailsFeatureConstructor(), "},{"kind":"externalParam","text":"myMealsContructor"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MyMealsFeatureConstructor","kind":"typeIdentifier","text":"MyMealsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK25MyMealsFeatureConstructorV"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyMealsFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:myMealsContructor:)"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MyMealsFeatureConstructor":{"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyMealsFeatureConstructor","kind":"identifier"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MyMealsFeatureConstructor","title":"MyMealsFeatureConstructor","url":"\/documentation\/mealziossdk\/mymealsfeatureconstructor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyMealsFeatureConstructor"}],"abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMyMealsFeatureUIKit/init(hideTitles:recipeDetailsConstructor:myMealsContructor:)":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyMealsFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:myMealsContructor:)","type":"topic","kind":"symbol","url":"\/documentation\/mealziossdk\/mealzmymealsfeatureuikit\/init(hidetitles:recipedetailsconstructor:mymealscontructor:)","title":"init(hideTitles:recipeDetailsConstructor:myMealsContructor:)","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"hideTitles","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"myMealsContructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK25MyMealsFeatureConstructorV","text":"MyMealsFeatureConstructor"},{"kind":"text","text":")"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMyMealsFeatureUIKit":{"title":"MealzMyMealsFeatureUIKit","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzMyMealsFeatureUIKit"}],"abstract":[],"navigatorTitle":[{"text":"MealzMyMealsFeatureUIKit","kind":"identifier"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyMealsFeatureUIKit","role":"symbol","url":"\/documentation\/mealziossdk\/mealzmymealsfeatureuikit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyMealsFeatureUIKit\/title","value":"MealzMyMealsFeatureUIKit","op":"replace"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyMealsFeatureUIKit\/fragments","op":"replace","value":[{"kind":"identifier","text":"MealzMyMealsFeatureUIKit"}]},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyMealsFeatureUIKit\/navigatorTitle","value":[{"kind":"identifier","text":"MealzMyMealsFeatureUIKit"}],"op":"replace"}]}]}