{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"kind":"text","text":" = RecipeDetailsFeatureConstructor(), "},{"text":"mySpaceConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MySpaceFeatureConstructor","text":"MySpaceFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK25MySpaceFeatureConstructorV"},{"kind":"text","text":" = MySpaceFeatureConstructor(), "},{"text":"catalogFeatureConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CatalogFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK25CatalogFeatureConstructorV","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/CatalogFeatureConstructor"},{"text":" = CatalogFeatureConstructor(), ","kind":"text"},{"kind":"externalParam","text":"myMealsViewOptions"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MyMealsViewOptions","text":"MyMealsViewOptions","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK18MyMealsViewOptionsV"},{"kind":"text","text":" = MyMealsViewOptions(), "},{"kind":"externalParam","text":"myMealsRecipesListGridConfig"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/CatalogRecipesListGridConfig","kind":"typeIdentifier","text":"CatalogRecipesListGridConfig","preciseIdentifier":"s:11MealziOSSDK28CatalogRecipesListGridConfigV"},{"kind":"text","text":" = myMealsDefaultRecipesListGridConfig, "},{"kind":"externalParam","text":"mealPlannerFeatureConstructor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK29MealPlannerFeatureConstructorV","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealPlannerFeatureConstructor","text":"MealPlannerFeatureConstructor","kind":"typeIdentifier"},{"kind":"text","text":" = MealPlannerFeatureConstructor(), "},{"text":"navigateToClientBasket","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mealziossdk\/mealzcatalogfeatureuikit\/init(hidetitles:recipedetailsconstructor:myspaceconstructor:catalogfeatureconstructor:mymealsviewoptions:mymealsrecipeslistgridconfig:mealplannerfeatureconstructor:navigatetoclientbasket:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:11MealziOSSDK24MealzCatalogFeatureUIKitC10hideTitles24recipeDetailsConstructor07mySpaceK007catalogeK00L16MealsViewOptions0lO21RecipesListGridConfig011mealPlannereK022navigateToClientBasketACSb_AA06RecipejeK0VAA02MymeK0VAA0deK0VAA02MyopQ0VAA0drstU0VAA04MealweK0VyycSgtcfc","platforms":[{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"14.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"14.0","beta":false,"unavailable":false,"deprecated":false}],"modules":[{"name":"MealziOSSDK"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"hideTitles","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"text":", ","kind":"text"},{"text":"mySpaceConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MySpaceFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK25MySpaceFeatureConstructorV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"catalogFeatureConstructor"},{"text":": ","kind":"text"},{"text":"CatalogFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK25CatalogFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"myMealsViewOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MyMealsViewOptions","preciseIdentifier":"s:11MealziOSSDK18MyMealsViewOptionsV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"myMealsRecipesListGridConfig"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK28CatalogRecipesListGridConfigV","kind":"typeIdentifier","text":"CatalogRecipesListGridConfig"},{"kind":"text","text":", "},{"text":"mealPlannerFeatureConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK29MealPlannerFeatureConstructorV","text":"MealPlannerFeatureConstructor"},{"kind":"text","text":", "},{"text":"navigateToClientBasket","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","roleHeading":"Initializer","title":"init(hideTitles:recipeDetailsConstructor:mySpaceConstructor:catalogFeatureConstructor:myMealsViewOptions:myMealsRecipesListGridConfig:mealPlannerFeatureConstructor:navigateToClientBasket:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit"]]},"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mySpaceConstructor:catalogFeatureConstructor:myMealsViewOptions:myMealsRecipesListGridConfig:mealPlannerFeatureConstructor:navigateToClientBasket:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzCatalogFeatureUIKit":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzCatalogFeatureUIKit"}],"role":"symbol","navigatorTitle":[{"text":"MealzCatalogFeatureUIKit","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mealziossdk\/mealzcatalogfeatureuikit","kind":"symbol","title":"MealzCatalogFeatureUIKit","type":"topic"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/CatalogFeatureConstructor":{"kind":"symbol","title":"CatalogFeatureConstructor","url":"\/documentation\/mealziossdk\/catalogfeatureconstructor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CatalogFeatureConstructor"}],"abstract":[],"navigatorTitle":[{"text":"CatalogFeatureConstructor","kind":"identifier"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/CatalogFeatureConstructor","type":"topic","role":"symbol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MyMealsViewOptions":{"abstract":[{"type":"text","text":"The optional View parameters for MyMeals. If nothing is passed in, the Miam Default will be used"}],"type":"topic","kind":"symbol","role":"symbol","title":"MyMealsViewOptions","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyMealsViewOptions","kind":"identifier"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MyMealsViewOptions","navigatorTitle":[{"text":"MyMealsViewOptions","kind":"identifier"}],"url":"\/documentation\/mealziossdk\/mymealsviewoptions"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealPlannerFeatureConstructor":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealPlannerFeatureConstructor","abstract":[],"kind":"symbol","type":"topic","title":"MealPlannerFeatureConstructor","url":"\/documentation\/mealziossdk\/mealplannerfeatureconstructor","navigatorTitle":[{"text":"MealPlannerFeatureConstructor","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MealPlannerFeatureConstructor","kind":"identifier"}],"role":"symbol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MySpaceFeatureConstructor":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MySpaceFeatureConstructor","abstract":[],"kind":"symbol","type":"topic","title":"MySpaceFeatureConstructor","url":"\/documentation\/mealziossdk\/myspacefeatureconstructor","navigatorTitle":[{"text":"MySpaceFeatureConstructor","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MySpaceFeatureConstructor","kind":"identifier"}],"role":"symbol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzCatalogFeatureUIKit/init(hideTitles:recipeDetailsConstructor:mySpaceConstructor:catalogFeatureConstructor:myMealsViewOptions:myMealsRecipesListGridConfig:mealPlannerFeatureConstructor:navigateToClientBasket:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mySpaceConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MySpaceFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK25MySpaceFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"catalogFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK25CatalogFeatureConstructorV","text":"CatalogFeatureConstructor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"myMealsViewOptions"},{"text":": ","kind":"text"},{"text":"MyMealsViewOptions","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK18MyMealsViewOptionsV"},{"text":", ","kind":"text"},{"text":"myMealsRecipesListGridConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK28CatalogRecipesListGridConfigV","text":"CatalogRecipesListGridConfig"},{"kind":"text","text":", "},{"text":"mealPlannerFeatureConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK29MealPlannerFeatureConstructorV","text":"MealPlannerFeatureConstructor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"navigateToClientBasket"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mySpaceConstructor:catalogFeatureConstructor:myMealsViewOptions:myMealsRecipesListGridConfig:mealPlannerFeatureConstructor:navigateToClientBasket:)","role":"symbol","abstract":[],"title":"init(hideTitles:recipeDetailsConstructor:mySpaceConstructor:catalogFeatureConstructor:myMealsViewOptions:myMealsRecipesListGridConfig:mealPlannerFeatureConstructor:navigateToClientBasket:)","url":"\/documentation\/mealziossdk\/mealzcatalogfeatureuikit\/init(hidetitles:recipedetailsconstructor:myspaceconstructor:catalogfeatureconstructor:mymealsviewoptions:mymealsrecipeslistgridconfig:mealplannerfeatureconstructor:navigatetoclientbasket:)","kind":"symbol","type":"topic"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/CatalogRecipesListGridConfig":{"url":"\/documentation\/mealziossdk\/catalogrecipeslistgridconfig","abstract":[{"type":"text","text":"Configuration for the grid constraints of the CatalogRecipes List"}],"title":"CatalogRecipesListGridConfig","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/CatalogRecipesListGridConfig","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"CatalogRecipesListGridConfig","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CatalogRecipesListGridConfig"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzCatalogFeatureUIKit\/title","op":"replace","value":"MealzCatalogFeatureUIKit"},{"value":[{"text":"MealzCatalogFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzCatalogFeatureUIKit\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MealzCatalogFeatureUIKit"}],"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzCatalogFeatureUIKit\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}