{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit\/openCatalogResults(catalogId:categoryTitle:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"openCatalogResults","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"catalogId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"categoryTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzcatalogfeatureuikit\/opencatalogresults(catalogid:categorytitle:)"]}],"metadata":{"externalID":"s:11MealziOSSDK24MealzCatalogFeatureUIKitC04openD7Results9catalogId13categoryTitleySSSg_AGtF","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","platforms":[{"beta":false,"name":"iOS","introducedAt":"14.0","unavailable":false,"deprecated":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"14.0","unavailable":false},{"introducedAt":"14.0","unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false}],"modules":[{"name":"MealziOSSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"openCatalogResults"},{"kind":"text","text":"("},{"text":"catalogId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"categoryTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"title":"openCatalogResults(catalogId:categoryTitle:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit"]]},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzCatalogFeatureUIKit/openCatalogResults(catalogId:categoryTitle:)":{"abstract":[],"url":"\/documentation\/mealziossdk\/mealzcatalogfeatureuikit\/opencatalogresults(catalogid:categorytitle:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openCatalogResults"},{"text":"(","kind":"text"},{"text":"catalogId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"categoryTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit\/openCatalogResults(catalogId:categoryTitle:)","kind":"symbol","title":"openCatalogResults(catalogId:categoryTitle:)"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzCatalogFeatureUIKit":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzCatalogFeatureUIKit"}],"role":"symbol","navigatorTitle":[{"text":"MealzCatalogFeatureUIKit","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mealziossdk\/mealzcatalogfeatureuikit","kind":"symbol","title":"MealzCatalogFeatureUIKit","type":"topic"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzCatalogFeatureUIKit\/title","value":"MealzCatalogFeatureUIKit","op":"replace"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzCatalogFeatureUIKit\/fragments","op":"replace","value":[{"kind":"identifier","text":"MealzCatalogFeatureUIKit"}]},{"value":[{"text":"MealzCatalogFeatureUIKit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzCatalogFeatureUIKit\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}