{"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMealPlannerFeatureUIKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"hideTitles","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"text":" = RecipeDetailsFeatureConstructor(), ","kind":"text"},{"kind":"externalParam","text":"mealPlannerFeatureConstructor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK29MealPlannerFeatureConstructorV","text":"MealPlannerFeatureConstructor","kind":"typeIdentifier","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealPlannerFeatureConstructor"},{"text":" = MealPlannerFeatureConstructor())","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzmealplannerfeatureuikit\/init(hidetitles:recipedetailsconstructor:mealplannerfeatureconstructor:)"]}],"metadata":{"role":"symbol","symbolKind":"init","platforms":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"14.0","unavailable":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"introducedAt":"14.0","beta":false,"deprecated":false,"name":"Mac Catalyst"}],"title":"init(hideTitles:recipeDetailsConstructor:mealPlannerFeatureConstructor:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mealPlannerFeatureConstructor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK29MealPlannerFeatureConstructorV","kind":"typeIdentifier","text":"MealPlannerFeatureConstructor"},{"kind":"text","text":")"}],"externalID":"s:11MealziOSSDK28MealzMealPlannerFeatureUIKitC10hideTitles24recipeDetailsConstructor04mealefL0ACSb_AA06RecipekfL0VAA0defL0Vtcfc","roleHeading":"Initializer","modules":[{"name":"MealziOSSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMealPlannerFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mealPlannerFeatureConstructor:)"},"sections":[],"kind":"symbol","references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMealPlannerFeatureUIKit":{"type":"topic","abstract":[],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMealPlannerFeatureUIKit","navigatorTitle":[{"text":"MealzMealPlannerFeatureUIKit","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MealzMealPlannerFeatureUIKit","kind":"identifier"}],"url":"\/documentation\/mealziossdk\/mealzmealplannerfeatureuikit","role":"symbol","title":"MealzMealPlannerFeatureUIKit"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealPlannerFeatureConstructor":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealPlannerFeatureConstructor","abstract":[],"kind":"symbol","type":"topic","title":"MealPlannerFeatureConstructor","url":"\/documentation\/mealziossdk\/mealplannerfeatureconstructor","navigatorTitle":[{"text":"MealPlannerFeatureConstructor","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MealPlannerFeatureConstructor","kind":"identifier"}],"role":"symbol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMealPlannerFeatureUIKit/init(hideTitles:recipeDetailsConstructor:mealPlannerFeatureConstructor:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMealPlannerFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mealPlannerFeatureConstructor:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"hideTitles"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mealPlannerFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK29MealPlannerFeatureConstructorV","text":"MealPlannerFeatureConstructor"},{"text":")","kind":"text"}],"url":"\/documentation\/mealziossdk\/mealzmealplannerfeatureuikit\/init(hidetitles:recipedetailsconstructor:mealplannerfeatureconstructor:)","role":"symbol","title":"init(hideTitles:recipeDetailsConstructor:mealPlannerFeatureConstructor:)"}},"variantOverrides":[{"patch":[{"value":"MealzMealPlannerFeatureUIKit","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMealPlannerFeatureUIKit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MealzMealPlannerFeatureUIKit"}],"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMealPlannerFeatureUIKit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMealPlannerFeatureUIKit\/navigatorTitle","value":[{"kind":"identifier","text":"MealzMealPlannerFeatureUIKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}