{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"retailerProductId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scrollAlignment"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4AxisO","kind":"typeIdentifier","text":"Axis"},{"text":".","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4AxisO3SetV","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":" = .horizontal, "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor"},{"kind":"text","text":" = RecipeDetailsFeatureConstructor(), "},{"kind":"externalParam","text":"basketTagFeatureConstructor"},{"kind":"text","text":": "},{"text":"BasketTagFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK27BasketTagFeatureConstructorV","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/BasketTagFeatureConstructor","kind":"typeIdentifier"},{"kind":"text","text":" = BasketTagFeatureConstructor())"}]}]}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Initializer","symbolKind":"init","platforms":[{"deprecated":false,"introducedAt":"14.0","beta":false,"name":"iOS","unavailable":false},{"unavailable":false,"introducedAt":"14.0","name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"14.0","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false}],"title":"init(retailerProductId:scrollAlignment:recipeDetailsConstructor:basketTagFeatureConstructor:)","externalID":"s:11MealziOSSDK26MealzBasketTagFeatureUIKitC17retailerProductId15scrollAlignment24recipeDetailsConstructor06basketefO0ACSS_7SwiftUI4AxisO3SetVAA06RecipenfO0VAA0defO0Vtcfc","modules":[{"name":"MealziOSSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"retailerProductId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scrollAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Axis","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4AxisO"},{"text":".","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4AxisO3SetV","kind":"typeIdentifier","text":"Set"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"basketTagFeatureConstructor"},{"text":": ","kind":"text"},{"text":"BasketTagFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK27BasketTagFeatureConstructorV"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit"]]},"variants":[{"paths":["\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit\/init(retailerproductid:scrollalignment:recipedetailsconstructor:baskettagfeatureconstructor:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit\/init(retailerProductId:scrollAlignment:recipeDetailsConstructor:basketTagFeatureConstructor:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/BasketTagFeatureConstructor":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"BasketTagFeatureConstructor","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BasketTagFeatureConstructor","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/BasketTagFeatureConstructor","title":"BasketTagFeatureConstructor","url":"\/documentation\/mealziossdk\/baskettagfeatureconstructor"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzBasketTagFeatureUIKit":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit","type":"topic","navigatorTitle":[{"text":"MealzBasketTagFeatureUIKit","kind":"identifier"}],"url":"\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"}],"title":"MealzBasketTagFeatureUIKit"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzBasketTagFeatureUIKit/init(retailerProductId:scrollAlignment:recipeDetailsConstructor:basketTagFeatureConstructor:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"retailerProductId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"scrollAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Axis","preciseIdentifier":"s:7SwiftUI4AxisO","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4AxisO3SetV","text":"Set"},{"kind":"text","text":", "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"kind":"text","text":", "},{"text":"basketTagFeatureConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BasketTagFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK27BasketTagFeatureConstructorV"},{"kind":"text","text":")"}],"title":"init(retailerProductId:scrollAlignment:recipeDetailsConstructor:basketTagFeatureConstructor:)","kind":"symbol","type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit\/init(retailerProductId:scrollAlignment:recipeDetailsConstructor:basketTagFeatureConstructor:)","url":"\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit\/init(retailerproductid:scrollalignment:recipedetailsconstructor:baskettagfeatureconstructor:)","role":"symbol","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MealzBasketTagFeatureUIKit","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit\/title","op":"replace"},{"op":"replace","value":[{"text":"MealzBasketTagFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit\/fragments"},{"value":[{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit\/navigatorTitle","op":"replace"}]}]}