{"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit\/viewdidload()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit\/viewdidload()"]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit\/viewDidLoad()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"MealziOSSDK"}],"externalID":"c:@M@MealziOSSDK@objc(cs)MealzBasketTagFeatureUIKit(im)viewDidLoad","title":"viewDidLoad()","platforms":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"14.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"14.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"14.0","unavailable":false}]},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzBasketTagFeatureUIKit":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit","type":"topic","navigatorTitle":[{"text":"MealzBasketTagFeatureUIKit","kind":"identifier"}],"url":"\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"}],"title":"MealzBasketTagFeatureUIKit"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzBasketTagFeatureUIKit/viewDidLoad()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit\/viewDidLoad()","url":"\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit\/viewdidload()","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"role":"symbol","title":"viewDidLoad()","abstract":[],"type":"topic"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"viewDidLoad","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"viewDidLoad","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"MealzBasketTagFeatureUIKit","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit\/title"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit\/fragments","op":"replace","value":[{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"}]},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit\/navigatorTitle","value":[{"text":"MealzBasketTagFeatureUIKit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit~1viewDidLoad()\/title","value":"viewDidLoad"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit~1viewDidLoad()\/fragments","op":"replace"}]}]}