{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"criteria","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MealzcoreSuggestionsCriteria","text":"SuggestionsCriteria","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"numberOfResults","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor"},{"text":" = RecipeDetailsFeatureConstructor(), ","kind":"text"},{"kind":"externalParam","text":"recipeCarouselFeatureConstructor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK32RecipeCarouselFeatureConstructorV","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeCarouselFeatureConstructor","kind":"typeIdentifier","text":"RecipeCarouselFeatureConstructor"},{"kind":"text","text":" = RecipeCarouselFeatureConstructor())"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"criteria"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MealzcoreSuggestionsCriteria","text":"SuggestionsCriteria"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"recipeCarouselFeatureConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK32RecipeCarouselFeatureConstructorV","text":"RecipeCarouselFeatureConstructor","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(criteria:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)","externalID":"s:11MealziOSSDK31MealzRecipeCarouselFeatureUIKitC8criteria15numberOfResults24recipeDetailsConstructor0lefN0ACSo28MealzcoreSuggestionsCriteriaC_SiAA0dmfN0VAA0defN0Vtcfc","role":"symbol","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"MealziOSSDK"}],"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false,"beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","beta":false,"name":"Mac Catalyst"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit\/init(criteria:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit\/init(criteria:numberofresults:recipedetailsconstructor:recipecarouselfeatureconstructor:)"]}],"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeCarouselFeatureUIKit":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit","navigatorTitle":[{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}],"title":"MealzRecipeCarouselFeatureUIKit","url":"\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit","role":"symbol","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeCarouselFeatureUIKit/init(criteria:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)":{"type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"criteria"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SuggestionsCriteria","preciseIdentifier":"c:objc(cs)MealzcoreSuggestionsCriteria"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfResults"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeCarouselFeatureConstructor"},{"kind":"text","text":": "},{"text":"RecipeCarouselFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK32RecipeCarouselFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit\/init(criteria:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)","url":"\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit\/init(criteria:numberofresults:recipedetailsconstructor:recipecarouselfeatureconstructor:)","title":"init(criteria:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)","kind":"symbol","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeCarouselFeatureConstructor":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeCarouselFeatureConstructor","navigatorTitle":[{"text":"RecipeCarouselFeatureConstructor","kind":"identifier"}],"abstract":[],"type":"topic","title":"RecipeCarouselFeatureConstructor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecipeCarouselFeatureConstructor","kind":"identifier"}],"url":"\/documentation\/mealziossdk\/recipecarouselfeatureconstructor","kind":"symbol","role":"symbol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeCarouselFeatureUIKit\/title","value":"MealzRecipeCarouselFeatureUIKit","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MealzRecipeCarouselFeatureUIKit"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeCarouselFeatureUIKit\/fragments"},{"value":[{"kind":"identifier","text":"MealzRecipeCarouselFeatureUIKit"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeCarouselFeatureUIKit\/navigatorTitle","op":"replace"}]}]}