{"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit\/init(productId:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)","interfaceLanguage":"swift"},"metadata":{"externalID":"s:11MealziOSSDK31MealzRecipeCarouselFeatureUIKitC9productId15numberOfResults24recipeDetailsConstructor0mefO0ACSS_SiAA0dnfO0VAA0defO0Vtcfc","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS"},{"introducedAt":"14.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"14.0","beta":false}],"role":"symbol","roleHeading":"Initializer","modules":[{"name":"MealziOSSDK"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"productId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"numberOfResults","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"text":", ","kind":"text"},{"text":"recipeCarouselFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RecipeCarouselFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK32RecipeCarouselFeatureConstructorV"},{"kind":"text","text":")"}],"title":"init(productId:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"productId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfResults"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"text":"RecipeDetailsFeatureConstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":" = RecipeDetailsFeatureConstructor(), "},{"kind":"externalParam","text":"recipeCarouselFeatureConstructor"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeCarouselFeatureConstructor","text":"RecipeCarouselFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK32RecipeCarouselFeatureConstructorV"},{"text":" = RecipeCarouselFeatureConstructor())","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit\/init(productid:numberofresults:recipedetailsconstructor:recipecarouselfeatureconstructor:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit"]]},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeCarouselFeatureUIKit/init(productId:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)":{"kind":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit\/init(productId:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)","title":"init(productId:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)","abstract":[],"type":"topic","url":"\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit\/init(productid:numberofresults:recipedetailsconstructor:recipecarouselfeatureconstructor:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"productId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"numberOfResults","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"kind":"text","text":", "},{"text":"recipeCarouselFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RecipeCarouselFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK32RecipeCarouselFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeCarouselFeatureConstructor":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeCarouselFeatureConstructor","navigatorTitle":[{"text":"RecipeCarouselFeatureConstructor","kind":"identifier"}],"abstract":[],"type":"topic","title":"RecipeCarouselFeatureConstructor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecipeCarouselFeatureConstructor","kind":"identifier"}],"url":"\/documentation\/mealziossdk\/recipecarouselfeatureconstructor","kind":"symbol","role":"symbol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeCarouselFeatureUIKit":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit","navigatorTitle":[{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}],"title":"MealzRecipeCarouselFeatureUIKit","url":"\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit","role":"symbol","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeCarouselFeatureUIKit\/title","value":"MealzRecipeCarouselFeatureUIKit"},{"value":[{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeCarouselFeatureUIKit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeCarouselFeatureUIKit\/navigatorTitle","value":[{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}