{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMySpaceFeatureUIKit"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"hideTitles","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","text":"RecipeDetailsFeatureConstructor"},{"text":" = RecipeDetailsFeatureConstructor(), ","kind":"text"},{"text":"mySpaceFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MySpaceFeatureConstructor","kind":"typeIdentifier","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MySpaceFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK25MySpaceFeatureConstructorV"},{"kind":"text","text":", "},{"text":"navigateToCatalog","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"navigateToClientBasket","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzmyspacefeatureuikit\/init(hidetitles:recipedetailsconstructor:myspacefeatureconstructor:navigatetocatalog:navigatetoclientbasket:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMySpaceFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mySpaceFeatureConstructor:navigateToCatalog:navigateToClientBasket:)"},"metadata":{"modules":[{"name":"MealziOSSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor"},{"text":", ","kind":"text"},{"text":"mySpaceFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK25MySpaceFeatureConstructorV","kind":"typeIdentifier","text":"MySpaceFeatureConstructor"},{"kind":"text","text":", "},{"text":"navigateToCatalog","kind":"externalParam"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"text":"navigateToClientBasket","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"platforms":[{"beta":false,"name":"iOS","introducedAt":"14.0","unavailable":false,"deprecated":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"deprecated":false}],"externalID":"s:11MealziOSSDK24MealzMySpaceFeatureUIKitC10hideTitles24recipeDetailsConstructor02myefL017navigateToCatalog0nO12ClientBasketACSb_AA06RecipekfL0VAA0defL0VyycyycSgtcfc","symbolKind":"init","role":"symbol","roleHeading":"Initializer","title":"init(hideTitles:recipeDetailsConstructor:mySpaceFeatureConstructor:navigateToCatalog:navigateToClientBasket:)"},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMySpaceFeatureUIKit/init(hideTitles:recipeDetailsConstructor:mySpaceFeatureConstructor:navigateToCatalog:navigateToClientBasket:)":{"role":"symbol","abstract":[],"url":"\/documentation\/mealziossdk\/mealzmyspacefeatureuikit\/init(hidetitles:recipedetailsconstructor:myspacefeatureconstructor:navigatetocatalog:navigatetoclientbasket:)","title":"init(hideTitles:recipeDetailsConstructor:mySpaceFeatureConstructor:navigateToCatalog:navigateToClientBasket:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"hideTitles","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mySpaceFeatureConstructor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MySpaceFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK25MySpaceFeatureConstructorV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"navigateToCatalog"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"navigateToClientBasket"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMySpaceFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mySpaceFeatureConstructor:navigateToCatalog:navigateToClientBasket:)","kind":"symbol","type":"topic"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MySpaceFeatureConstructor":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MySpaceFeatureConstructor","abstract":[],"kind":"symbol","type":"topic","title":"MySpaceFeatureConstructor","url":"\/documentation\/mealziossdk\/myspacefeatureconstructor","navigatorTitle":[{"text":"MySpaceFeatureConstructor","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MySpaceFeatureConstructor","kind":"identifier"}],"role":"symbol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMySpaceFeatureUIKit":{"role":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMySpaceFeatureUIKit","url":"\/documentation\/mealziossdk\/mealzmyspacefeatureuikit","navigatorTitle":[{"kind":"identifier","text":"MealzMySpaceFeatureUIKit"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzMySpaceFeatureUIKit"}],"title":"MealzMySpaceFeatureUIKit","type":"topic","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MealzMySpaceFeatureUIKit","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMySpaceFeatureUIKit\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MealzMySpaceFeatureUIKit"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMySpaceFeatureUIKit\/fragments"},{"value":[{"kind":"identifier","text":"MealzMySpaceFeatureUIKit"}],"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMySpaceFeatureUIKit\/navigatorTitle"}]}]}