{"variants":[{"paths":["\/documentation\/mealziossdk\/mealzorderhistoryfeatureuikit\/init(hidetitles:recipedetailsconstructor:orderhistoryfeatureconstructor:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderHistoryFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:orderHistoryFeatureConstructor:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"hideTitles","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"kind":"text","text":" = RecipeDetailsFeatureConstructor(), "},{"kind":"externalParam","text":"orderHistoryFeatureConstructor"},{"text":": ","kind":"text"},{"text":"OrderHistoryFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK30OrderHistoryFeatureConstructorV","kind":"typeIdentifier","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/OrderHistoryFeatureConstructor"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"title":"init(hideTitles:recipeDetailsConstructor:orderHistoryFeatureConstructor:)","externalID":"s:11MealziOSSDK29MealzOrderHistoryFeatureUIKitC10hideTitles24recipeDetailsConstructor05orderefL0ACSb_AA06RecipekfL0VAA0defL0Vtcfc","platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false,"introducedAt":"14.0"},{"name":"iPadOS","introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"Mac Catalyst","beta":false}],"roleHeading":"Initializer","modules":[{"name":"MealziOSSDK"}],"symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"hideTitles","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orderHistoryFeatureConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK30OrderHistoryFeatureConstructorV","text":"OrderHistoryFeatureConstructor"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderHistoryFeatureUIKit"]]},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzOrderHistoryFeatureUIKit/init(hideTitles:recipeDetailsConstructor:orderHistoryFeatureConstructor:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderHistoryFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:orderHistoryFeatureConstructor:)","url":"\/documentation\/mealziossdk\/mealzorderhistoryfeatureuikit\/init(hidetitles:recipedetailsconstructor:orderhistoryfeatureconstructor:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"hideTitles","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"text":", ","kind":"text"},{"text":"orderHistoryFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK30OrderHistoryFeatureConstructorV","text":"OrderHistoryFeatureConstructor"},{"text":")","kind":"text"}],"title":"init(hideTitles:recipeDetailsConstructor:orderHistoryFeatureConstructor:)","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzOrderHistoryFeatureUIKit":{"title":"MealzOrderHistoryFeatureUIKit","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderHistoryFeatureUIKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}],"url":"\/documentation\/mealziossdk\/mealzorderhistoryfeatureuikit"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/OrderHistoryFeatureConstructor":{"url":"\/documentation\/mealziossdk\/orderhistoryfeatureconstructor","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"OrderHistoryFeatureConstructor","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OrderHistoryFeatureConstructor"}],"type":"topic","title":"OrderHistoryFeatureConstructor","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/OrderHistoryFeatureConstructor"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderHistoryFeatureUIKit\/title","op":"replace","value":"MealzOrderHistoryFeatureUIKit"},{"value":[{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderHistoryFeatureUIKit\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderHistoryFeatureUIKit\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}