{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderDetailsFeatureUIKit\/init(hideTitles:orderDate:basketId:recipes:recipeDetailsConstructor:orderDetailsFeatureConstructor:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderDetailsFeatureUIKit"]]},"metadata":{"symbolKind":"init","modules":[{"name":"MealziOSSDK"}],"title":"init(hideTitles:orderDate:basketId:recipes:recipeDetailsConstructor:orderDetailsFeatureConstructor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hideTitles"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orderDate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"basketId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK14RecipeCardDataV","text":"RecipeCardData"},{"kind":"text","text":"], "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"orderDetailsFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"OrderDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK30OrderDetailsFeatureConstructorV"},{"text":")","kind":"text"}],"roleHeading":"Initializer","platforms":[{"name":"iOS","beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false},{"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iPadOS","beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false}],"role":"symbol","externalID":"s:11MealziOSSDK29MealzOrderDetailsFeatureUIKitC10hideTitles9orderDate8basketId7recipes06recipeE11Constructor0jefP0ACSb_S2SSayAA14RecipeCardDataVGAA0qefP0VAA0defP0Vtcfc"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzorderdetailsfeatureuikit\/init(hidetitles:orderdate:basketid:recipes:recipedetailsconstructor:orderdetailsfeatureconstructor:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"hideTitles","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"text":"orderDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"basketId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"recipes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"RecipeCardData","kind":"typeIdentifier","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeCardData","preciseIdentifier":"s:11MealziOSSDK14RecipeCardDataV"},{"text":"], ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor"},{"text":" = RecipeDetailsFeatureConstructor(), ","kind":"text"},{"text":"orderDetailsFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"OrderDetailsFeatureConstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/OrderDetailsFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK30OrderDetailsFeatureConstructorV"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzOrderDetailsFeatureUIKit":{"kind":"symbol","url":"\/documentation\/mealziossdk\/mealzorderdetailsfeatureuikit","role":"symbol","type":"topic","title":"MealzOrderDetailsFeatureUIKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MealzOrderDetailsFeatureUIKit","kind":"identifier"}],"navigatorTitle":[{"text":"MealzOrderDetailsFeatureUIKit","kind":"identifier"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderDetailsFeatureUIKit","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeCardData":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeCardData","kind":"identifier"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeCardData","title":"RecipeCardData","role":"symbol","type":"topic","url":"\/documentation\/mealziossdk\/recipecarddata","navigatorTitle":[{"kind":"identifier","text":"RecipeCardData"}],"abstract":[],"kind":"symbol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzOrderDetailsFeatureUIKit/init(hideTitles:orderDate:basketId:recipes:recipeDetailsConstructor:orderDetailsFeatureConstructor:)":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderDetailsFeatureUIKit\/init(hideTitles:orderDate:basketId:recipes:recipeDetailsConstructor:orderDetailsFeatureConstructor:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orderDate"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"basketId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"recipes","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:11MealziOSSDK14RecipeCardDataV","kind":"typeIdentifier","text":"RecipeCardData"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor"},{"text":", ","kind":"text"},{"text":"orderDetailsFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK30OrderDetailsFeatureConstructorV","kind":"typeIdentifier","text":"OrderDetailsFeatureConstructor"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"init(hideTitles:orderDate:basketId:recipes:recipeDetailsConstructor:orderDetailsFeatureConstructor:)","url":"\/documentation\/mealziossdk\/mealzorderdetailsfeatureuikit\/init(hidetitles:orderdate:basketid:recipes:recipedetailsconstructor:orderdetailsfeatureconstructor:)"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/OrderDetailsFeatureConstructor":{"kind":"symbol","url":"\/documentation\/mealziossdk\/orderdetailsfeatureconstructor","role":"symbol","type":"topic","title":"OrderDetailsFeatureConstructor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"OrderDetailsFeatureConstructor","kind":"identifier"}],"navigatorTitle":[{"text":"OrderDetailsFeatureConstructor","kind":"identifier"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/OrderDetailsFeatureConstructor","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MealzOrderDetailsFeatureUIKit","op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderDetailsFeatureUIKit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MealzOrderDetailsFeatureUIKit"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderDetailsFeatureUIKit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderDetailsFeatureUIKit\/navigatorTitle","value":[{"text":"MealzOrderDetailsFeatureUIKit","kind":"identifier"}]}]}]}