{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MealziOSSDK"}],"title":"MealzStandaloneRecipeCardUIKit","roleHeading":"Class","navigatorTitle":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MealziOSSDK@objc(cs)MealzStandaloneRecipeCardUIKit","symbolKind":"class","platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"14.0","name":"iPadOS"},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}]},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UIViewController"],"kind":"relationships"},{"identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/s8SendableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit"]},{"paths":["\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(criteria:recipeDetailsConstructor:recipeCardConstructor:)","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(recipe:recipeDetailsConstructor:recipeCardConstructor:)","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(recipeId:isMealzRecipe:recipeDetailsConstructor:recipeCardConstructor:)"],"generated":true,"title":"Initializers"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/viewDidLoad()"],"anchor":"Instance-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}]}]}],"sections":[],"references":{"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://mealz.MealziOSSDK/SQ":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit/init(recipe:recipeDetailsConstructor:recipeCardConstructor:)":{"title":"init(recipe:recipeDetailsConstructor:recipeCardConstructor:)","role":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(recipe:recipeDetailsConstructor:recipeCardConstructor:)","url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/init(recipe:recipedetailsconstructor:recipecardconstructor:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"recipe","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Recipe","preciseIdentifier":"c:objc(cs)MealzcoreRecipe"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor"},{"kind":"text","text":", "},{"text":"recipeCardConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV","text":"StandaloneRecipeCardConstructor"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[]},"doc://mealz.MealziOSSDK/objc(cs)UIViewController":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit/viewDidLoad()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"type":"topic","url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/viewdidload()","role":"symbol","kind":"symbol","title":"viewDidLoad()","abstract":[],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/viewDidLoad()"},"doc://mealz.MealziOSSDK/s8SendableP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit":{"url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit","abstract":[],"navigatorTitle":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}],"title":"MealzStandaloneRecipeCardUIKit","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit/init(criteria:recipeDetailsConstructor:recipeCardConstructor:)":{"url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/init(criteria:recipedetailsconstructor:recipecardconstructor:)","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(criteria:recipeDetailsConstructor:recipeCardConstructor:)","abstract":[],"title":"init(criteria:recipeDetailsConstructor:recipeCardConstructor:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"criteria","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SuggestionsCriteria","preciseIdentifier":"c:objc(cs)MealzcoreSuggestionsCriteria","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"text":", ","kind":"text"},{"text":"recipeCardConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV","text":"StandaloneRecipeCardConstructor","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzStandaloneRecipeCardUIKit/init(recipeId:isMealzRecipe:recipeDetailsConstructor:recipeCardConstructor:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recipeId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isMealzRecipe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeCardConstructor"},{"text":": ","kind":"text"},{"text":"StandaloneRecipeCardConstructor","preciseIdentifier":"s:11MealziOSSDK31StandaloneRecipeCardConstructorV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/mealziossdk\/mealzstandalonerecipecarduikit\/init(recipeid:ismealzrecipe:recipedetailsconstructor:recipecardconstructor:)","title":"init(recipeId:isMealzRecipe:recipeDetailsConstructor:recipeCardConstructor:)","abstract":[],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/init(recipeId:isMealzRecipe:recipeDetailsConstructor:recipeCardConstructor:)","kind":"symbol","role":"symbol"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://mealz.MealziOSSDK/SH":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MealzStandaloneRecipeCardUIKit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzStandaloneRecipeCardUIKit\/viewDidLoad()"],"generated":true,"anchor":"Instance-Methods"}]},{"value":[{"identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UIViewController"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit~1viewDidLoad()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit~1viewDidLoad()\/fragments"},{"op":"replace","value":"MealzStandaloneRecipeCardUIKit","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/title"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/fragments","value":[{"text":"MealzStandaloneRecipeCardUIKit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzStandaloneRecipeCardUIKit\/navigatorTitle","value":[{"kind":"identifier","text":"MealzStandaloneRecipeCardUIKit"}]}]}]}