{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzRecipeCarouselFeatureUIKit"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}],"modules":[{"name":"MealziOSSDK"}],"platforms":[{"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"14.0","unavailable":false,"deprecated":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false}],"title":"MealzRecipeCarouselFeatureUIKit","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@MealziOSSDK@objc(cs)MealzRecipeCarouselFeatureUIKit","symbolKind":"class"},"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UIViewController"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/s8SendableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit"]}],"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit\/init(criteria:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit\/init(productId:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)"],"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit\/viewDidLoad()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"references":{"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeCarouselFeatureUIKit":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit","navigatorTitle":[{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}],"title":"MealzRecipeCarouselFeatureUIKit","url":"\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit","role":"symbol","abstract":[]},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://mealz.MealziOSSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/SQ","title":"Swift.Equatable"},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeCarouselFeatureUIKit/viewDidLoad()":{"url":"\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit\/viewdidload()","kind":"symbol","role":"symbol","title":"viewDidLoad()","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit\/viewDidLoad()"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://mealz.MealziOSSDK/objc(cs)UIViewController":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UIViewController","title":"UIViewController"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeCarouselFeatureUIKit/init(productId:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)":{"kind":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit\/init(productId:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)","title":"init(productId:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)","abstract":[],"type":"topic","url":"\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit\/init(productid:numberofresults:recipedetailsconstructor:recipecarouselfeatureconstructor:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"productId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"numberOfResults","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"kind":"text","text":", "},{"text":"recipeCarouselFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RecipeCarouselFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK32RecipeCarouselFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://mealz.MealziOSSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/SH"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeCarouselFeatureUIKit/init(criteria:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)":{"type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"criteria"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SuggestionsCriteria","preciseIdentifier":"c:objc(cs)MealzcoreSuggestionsCriteria"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfResults"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeCarouselFeatureConstructor"},{"kind":"text","text":": "},{"text":"RecipeCarouselFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK32RecipeCarouselFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit\/init(criteria:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)","url":"\/documentation\/mealziossdk\/mealzrecipecarouselfeatureuikit\/init(criteria:numberofresults:recipedetailsconstructor:recipecarouselfeatureconstructor:)","title":"init(criteria:numberOfResults:recipeDetailsConstructor:recipeCarouselFeatureConstructor:)","kind":"symbol","abstract":[]},"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding"},"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer"},"doc://mealz.MealziOSSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s8SendableP"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst"}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MealzRecipeCarouselFeatureUIKit"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MealzRecipeCarouselFeatureUIKit"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeCarouselFeatureUIKit\/viewDidLoad()"],"title":"Instance Methods"}]},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UIViewController"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeCarouselFeatureUIKit\/title","value":"MealzRecipeCarouselFeatureUIKit"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeCarouselFeatureUIKit\/fragments","op":"replace","value":[{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeCarouselFeatureUIKit\/navigatorTitle","value":[{"text":"MealzRecipeCarouselFeatureUIKit","kind":"identifier"}]},{"value":"viewDidLoad","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeCarouselFeatureUIKit~1viewDidLoad()\/title","op":"replace"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeCarouselFeatureUIKit~1viewDidLoad()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}]}]}]}