{"sections":[],"variants":[{"paths":["\/documentation\/mealziossdk\/mealzmyspacefeatureuikit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mealziossdk\/mealzmyspacefeatureuikit"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzMySpaceFeatureUIKit"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"metadata":{"symbolKind":"class","modules":[{"name":"MealziOSSDK"}],"externalID":"c:@M@MealziOSSDK@objc(cs)MealzMySpaceFeatureUIKit","navigatorTitle":[{"kind":"identifier","text":"MealzMySpaceFeatureUIKit"}],"platforms":[{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"introducedAt":"14.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"beta":false}],"title":"MealzMySpaceFeatureUIKit","role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzMySpaceFeatureUIKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"]}],"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMySpaceFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mySpaceFeatureConstructor:navigateToCatalog:navigateToClientBasket:)"],"anchor":"Initializers"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMySpaceFeatureUIKit"},"references":{"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMySpaceFeatureUIKit":{"role":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMySpaceFeatureUIKit","url":"\/documentation\/mealziossdk\/mealzmyspacefeatureuikit","navigatorTitle":[{"kind":"identifier","text":"MealzMySpaceFeatureUIKit"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzMySpaceFeatureUIKit"}],"title":"MealzMySpaceFeatureUIKit","type":"topic","abstract":[]},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://mealz.MealziOSSDK/SH":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://mealz.MealziOSSDK/SQ":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(cs)UINavigationController":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController","title":"UINavigationController","type":"unresolvable"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMySpaceFeatureUIKit/init(hideTitles:recipeDetailsConstructor:mySpaceFeatureConstructor:navigateToCatalog:navigateToClientBasket:)":{"role":"symbol","abstract":[],"url":"\/documentation\/mealziossdk\/mealzmyspacefeatureuikit\/init(hidetitles:recipedetailsconstructor:myspacefeatureconstructor:navigatetocatalog:navigatetoclientbasket:)","title":"init(hideTitles:recipeDetailsConstructor:mySpaceFeatureConstructor:navigateToCatalog:navigateToClientBasket:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"hideTitles","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mySpaceFeatureConstructor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MySpaceFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK25MySpaceFeatureConstructorV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"navigateToCatalog"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"navigateToClientBasket"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMySpaceFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mySpaceFeatureConstructor:navigateToCatalog:navigateToClientBasket:)","kind":"symbol","type":"topic"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"14.0","name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"14.0","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false}],"op":"replace","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MealzMySpaceFeatureUIKit"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MealzMySpaceFeatureUIKit"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MealzMySpaceFeatureUIKit","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzMySpaceFeatureUIKit"},{"text":" : ","kind":"text"},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMySpaceFeatureUIKit\/title","value":"MealzMySpaceFeatureUIKit"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMySpaceFeatureUIKit\/fragments","value":[{"text":"MealzMySpaceFeatureUIKit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMySpaceFeatureUIKit\/navigatorTitle","op":"replace","value":[{"text":"MealzMySpaceFeatureUIKit","kind":"identifier"}]}]}]}