{"kind":"symbol","variants":[{"paths":["\/documentation\/mealziossdk\/mealzmymealsfeatureuikit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mealziossdk\/mealzmymealsfeatureuikit"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyMealsFeatureUIKit"},"topicSections":[{"identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyMealsFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:myMealsContructor:)"],"generated":true,"title":"Initializers","anchor":"Initializers"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzMyMealsFeatureUIKit"}],"languages":["swift"]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/s8SendableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"metadata":{"role":"symbol","title":"MealzMyMealsFeatureUIKit","modules":[{"name":"MealziOSSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MealzMyMealsFeatureUIKit","kind":"identifier"}],"roleHeading":"Class","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS","introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"14.0","name":"Mac Catalyst"}],"symbolKind":"class","navigatorTitle":[{"text":"MealzMyMealsFeatureUIKit","kind":"identifier"}],"externalID":"c:@M@MealziOSSDK@objc(cs)MealzMyMealsFeatureUIKit"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMyMealsFeatureUIKit/init(hideTitles:recipeDetailsConstructor:myMealsContructor:)":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyMealsFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:myMealsContructor:)","type":"topic","kind":"symbol","url":"\/documentation\/mealziossdk\/mealzmymealsfeatureuikit\/init(hidetitles:recipedetailsconstructor:mymealscontructor:)","title":"init(hideTitles:recipeDetailsConstructor:myMealsContructor:)","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"hideTitles","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"myMealsContructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK25MyMealsFeatureConstructorV","text":"MyMealsFeatureConstructor"},{"kind":"text","text":")"}]},"doc://mealz.MealziOSSDK/SQ":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMyMealsFeatureUIKit":{"title":"MealzMyMealsFeatureUIKit","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzMyMealsFeatureUIKit"}],"abstract":[],"navigatorTitle":[{"text":"MealzMyMealsFeatureUIKit","kind":"identifier"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyMealsFeatureUIKit","role":"symbol","url":"\/documentation\/mealziossdk\/mealzmymealsfeatureuikit"},"doc://mealz.MealziOSSDK/SH":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://mealz.MealziOSSDK/objc(cs)UINavigationController":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController","type":"unresolvable","title":"UINavigationController"},"doc://mealz.MealziOSSDK/s8SendableP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","beta":false,"name":"iPadOS"},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"14.0"}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"MealzMyMealsFeatureUIKit","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MealzMyMealsFeatureUIKit","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MealzMyMealsFeatureUIKit"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"]}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzMyMealsFeatureUIKit"},{"text":" : ","kind":"text"},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyMealsFeatureUIKit\/title","value":"MealzMyMealsFeatureUIKit"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyMealsFeatureUIKit\/fragments","op":"replace","value":[{"text":"MealzMyMealsFeatureUIKit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyMealsFeatureUIKit\/navigatorTitle","value":[{"text":"MealzMyMealsFeatureUIKit","kind":"identifier"}]}]}]}