{"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/s8SendableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MealzMealPlannerFeatureUIKit","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMealPlannerFeatureUIKit"},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"metadata":{"externalID":"c:@M@MealziOSSDK@objc(cs)MealzMealPlannerFeatureUIKit","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"MealzMealPlannerFeatureUIKit"}],"title":"MealzMealPlannerFeatureUIKit","platforms":[{"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"14.0"},{"beta":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"unavailable":false}],"modules":[{"name":"MealziOSSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MealzMealPlannerFeatureUIKit","kind":"identifier"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzmealplannerfeatureuikit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mealziossdk\/mealzmealplannerfeatureuikit"]}],"topicSections":[{"identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMealPlannerFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mealPlannerFeatureConstructor:)"],"anchor":"Initializers","title":"Initializers","generated":true}],"references":{"doc://mealz.MealziOSSDK/SQ":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://mealz.MealziOSSDK/SH":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMealPlannerFeatureUIKit/init(hideTitles:recipeDetailsConstructor:mealPlannerFeatureConstructor:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMealPlannerFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mealPlannerFeatureConstructor:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"hideTitles"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mealPlannerFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK29MealPlannerFeatureConstructorV","text":"MealPlannerFeatureConstructor"},{"text":")","kind":"text"}],"url":"\/documentation\/mealziossdk\/mealzmealplannerfeatureuikit\/init(hidetitles:recipedetailsconstructor:mealplannerfeatureconstructor:)","role":"symbol","title":"init(hideTitles:recipeDetailsConstructor:mealPlannerFeatureConstructor:)"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMealPlannerFeatureUIKit":{"type":"topic","abstract":[],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMealPlannerFeatureUIKit","navigatorTitle":[{"text":"MealzMealPlannerFeatureUIKit","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MealzMealPlannerFeatureUIKit","kind":"identifier"}],"url":"\/documentation\/mealziossdk\/mealzmealplannerfeatureuikit","role":"symbol","title":"MealzMealPlannerFeatureUIKit"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP"},"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/objc(cs)UINavigationController":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController","title":"UINavigationController"},"doc://mealz.MealziOSSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s8SendableP","title":"Swift.Sendable"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"beta":false,"introducedAt":"14.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst"}],"path":"\/metadata\/platforms","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"MealzMealPlannerFeatureUIKit","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MealzMealPlannerFeatureUIKit"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MealzMealPlannerFeatureUIKit","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MealzMealPlannerFeatureUIKit","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController","kind":"typeIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MealzMealPlannerFeatureUIKit","op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMealPlannerFeatureUIKit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MealzMealPlannerFeatureUIKit"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMealPlannerFeatureUIKit\/fragments"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMealPlannerFeatureUIKit\/navigatorTitle","value":[{"kind":"identifier","text":"MealzMealPlannerFeatureUIKit"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}