{"metadata":{"externalID":"c:@M@MealziOSSDK@objc(cs)MealzMyBasketFeatureUIKit","roleHeading":"Class","role":"symbol","platforms":[{"deprecated":false,"beta":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"unavailable":false,"introducedAt":"14.0","deprecated":false,"beta":false,"name":"Mac Catalyst"}],"modules":[{"name":"MealziOSSDK"}],"title":"MealzMyBasketFeatureUIKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzMyBasketFeatureUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"MealzMyBasketFeatureUIKit"}],"symbolKind":"class"},"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyBasketFeatureUIKit","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/s8SendableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"]}],"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyBasketFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:myBasketContructor:)"]}],"variants":[{"paths":["\/documentation\/mealziossdk\/mealzmybasketfeatureuikit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mealziossdk\/mealzmybasketfeatureuikit"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MealzMyBasketFeatureUIKit","kind":"identifier"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"references":{"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMyBasketFeatureUIKit/init(hideTitles:recipeDetailsConstructor:myBasketContructor:)":{"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyBasketFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:myBasketContructor:)","title":"init(hideTitles:recipeDetailsConstructor:myBasketContructor:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor"},{"text":", ","kind":"text"},{"text":"myBasketContructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK26MyBasketFeatureConstructorV","kind":"typeIdentifier","text":"MyBasketFeatureConstructor"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/mealziossdk\/mealzmybasketfeatureuikit\/init(hidetitles:recipedetailsconstructor:mybasketcontructor:)"},"doc://mealz.MealziOSSDK/objc(cs)UINavigationController":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController","title":"UINavigationController"},"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMyBasketFeatureUIKit":{"url":"\/documentation\/mealziossdk\/mealzmybasketfeatureuikit","type":"topic","title":"MealzMyBasketFeatureUIKit","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyBasketFeatureUIKit","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MealzMyBasketFeatureUIKit","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MealzMyBasketFeatureUIKit"}],"kind":"symbol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer"},"doc://mealz.MealziOSSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/mealz.MealziOSSDK\/SH"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP"},"doc://mealz.MealziOSSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/mealz.MealziOSSDK\/SQ"},"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://mealz.MealziOSSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s8SendableP","title":"Swift.Sendable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"14.0","name":"Mac Catalyst"}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MealzMyBasketFeatureUIKit","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MealzMyBasketFeatureUIKit"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MealzMyBasketFeatureUIKit","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzMyBasketFeatureUIKit"},{"kind":"text","text":" : "},{"text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"MealzMyBasketFeatureUIKit","op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyBasketFeatureUIKit\/title"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyBasketFeatureUIKit\/fragments","value":[{"kind":"identifier","text":"MealzMyBasketFeatureUIKit"}]},{"value":[{"text":"MealzMyBasketFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyBasketFeatureUIKit\/navigatorTitle","op":"replace"}]}]}