{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzFavoritesFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:favoritesFeatureConstructor:)"],"anchor":"Initializers","generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"variants":[{"paths":["\/documentation\/mealziossdk\/mealzfavoritesfeatureuikit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mealziossdk\/mealzfavoritesfeatureuikit"]}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Class","title":"MealzFavoritesFeatureUIKit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzFavoritesFeatureUIKit"}],"externalID":"c:@M@MealziOSSDK@objc(cs)MealzFavoritesFeatureUIKit","symbolKind":"class","modules":[{"name":"MealziOSSDK"}],"platforms":[{"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"name":"iPadOS","deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"14.0"}],"navigatorTitle":[{"kind":"identifier","text":"MealzFavoritesFeatureUIKit"}]},"sections":[],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/s8SendableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MealzFavoritesFeatureUIKit","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzFavoritesFeatureUIKit"},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzFavoritesFeatureUIKit/init(hideTitles:recipeDetailsConstructor:favoritesFeatureConstructor:)":{"url":"\/documentation\/mealziossdk\/mealzfavoritesfeatureuikit\/init(hidetitles:recipedetailsconstructor:favoritesfeatureconstructor:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"favoritesFeatureConstructor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK27FavoritesFeatureConstructorV","text":"FavoritesFeatureConstructor"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"title":"init(hideTitles:recipeDetailsConstructor:favoritesFeatureConstructor:)","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzFavoritesFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:favoritesFeatureConstructor:)"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzFavoritesFeatureUIKit":{"url":"\/documentation\/mealziossdk\/mealzfavoritesfeatureuikit","navigatorTitle":[{"text":"MealzFavoritesFeatureUIKit","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzFavoritesFeatureUIKit"}],"role":"symbol","abstract":[],"title":"MealzFavoritesFeatureUIKit","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzFavoritesFeatureUIKit"},"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://mealz.MealziOSSDK/SQ":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://mealz.MealziOSSDK/s8SendableP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://mealz.MealziOSSDK/objc(cs)UINavigationController":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController","type":"unresolvable","title":"UINavigationController"},"doc://mealz.MealziOSSDK/SH":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"name":"iPadOS","beta":false},{"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false}],"op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MealzFavoritesFeatureUIKit"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"MealzFavoritesFeatureUIKit"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MealzFavoritesFeatureUIKit","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzFavoritesFeatureUIKit"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzFavoritesFeatureUIKit\/title","value":"MealzFavoritesFeatureUIKit","op":"replace"},{"op":"replace","value":[{"text":"MealzFavoritesFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzFavoritesFeatureUIKit\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MealzFavoritesFeatureUIKit"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzFavoritesFeatureUIKit\/navigatorTitle"}]}]}