{"topicSections":[{"identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderDetailsFeatureUIKit\/init(hideTitles:orderDate:basketId:recipes:recipeDetailsConstructor:orderDetailsFeatureConstructor:)"],"generated":true,"anchor":"Initializers","title":"Initializers"}],"variants":[{"paths":["\/documentation\/mealziossdk\/mealzorderdetailsfeatureuikit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mealziossdk\/mealzorderdetailsfeatureuikit"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MealzOrderDetailsFeatureUIKit","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/s8SendableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"sections":[],"metadata":{"externalID":"c:@M@MealziOSSDK@objc(cs)MealzOrderDetailsFeatureUIKit","modules":[{"name":"MealziOSSDK"}],"role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"MealzOrderDetailsFeatureUIKit","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MealzOrderDetailsFeatureUIKit","kind":"identifier"}],"roleHeading":"Class","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"14.0","name":"iOS"},{"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iPadOS","unavailable":false},{"introducedAt":"14.0","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false}],"title":"MealzOrderDetailsFeatureUIKit"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderDetailsFeatureUIKit"},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzOrderDetailsFeatureUIKit":{"kind":"symbol","url":"\/documentation\/mealziossdk\/mealzorderdetailsfeatureuikit","role":"symbol","type":"topic","title":"MealzOrderDetailsFeatureUIKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MealzOrderDetailsFeatureUIKit","kind":"identifier"}],"navigatorTitle":[{"text":"MealzOrderDetailsFeatureUIKit","kind":"identifier"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderDetailsFeatureUIKit","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/mealz.MealziOSSDK\/SQ"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzOrderDetailsFeatureUIKit/init(hideTitles:orderDate:basketId:recipes:recipeDetailsConstructor:orderDetailsFeatureConstructor:)":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderDetailsFeatureUIKit\/init(hideTitles:orderDate:basketId:recipes:recipeDetailsConstructor:orderDetailsFeatureConstructor:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orderDate"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"basketId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"recipes","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:11MealziOSSDK14RecipeCardDataV","kind":"typeIdentifier","text":"RecipeCardData"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor"},{"text":", ","kind":"text"},{"text":"orderDetailsFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK30OrderDetailsFeatureConstructorV","kind":"typeIdentifier","text":"OrderDetailsFeatureConstructor"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"init(hideTitles:orderDate:basketId:recipes:recipeDetailsConstructor:orderDetailsFeatureConstructor:)","url":"\/documentation\/mealziossdk\/mealzorderdetailsfeatureuikit\/init(hidetitles:orderdate:basketid:recipes:recipedetailsconstructor:orderdetailsfeatureconstructor:)"},"doc://mealz.MealziOSSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/mealz.MealziOSSDK\/SH"},"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP"},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject"},"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer"},"doc://mealz.MealziOSSDK/objc(cs)UINavigationController":{"type":"unresolvable","title":"UINavigationController","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"},"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer"},"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions"},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment"},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP"},"doc://mealz.MealziOSSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/mealz.MealziOSSDK\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"replace","value":[{"beta":false,"name":"iOS","introducedAt":"14.0","unavailable":false,"deprecated":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"14.0"},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"MealzOrderDetailsFeatureUIKit","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MealzOrderDetailsFeatureUIKit","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MealzOrderDetailsFeatureUIKit","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzOrderDetailsFeatureUIKit"},{"kind":"text","text":" : "},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MealzOrderDetailsFeatureUIKit","op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderDetailsFeatureUIKit\/title"},{"op":"replace","value":[{"text":"MealzOrderDetailsFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderDetailsFeatureUIKit\/fragments"},{"value":[{"kind":"identifier","text":"MealzOrderDetailsFeatureUIKit"}],"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderDetailsFeatureUIKit\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}