{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzorderhistoryfeatureuikit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mealziossdk\/mealzorderhistoryfeatureuikit"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/s8SendableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"]}],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderHistoryFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:orderHistoryFeatureConstructor:)"]}],"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}],"modules":[{"name":"MealziOSSDK"}],"externalID":"c:@M@MealziOSSDK@objc(cs)MealzOrderHistoryFeatureUIKit","platforms":[{"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"}],"navigatorTitle":[{"kind":"identifier","text":"MealzOrderHistoryFeatureUIKit"}],"roleHeading":"Class","role":"symbol","symbolKind":"class","title":"MealzOrderHistoryFeatureUIKit"},"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderHistoryFeatureUIKit","interfaceLanguage":"swift"},"references":{"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment"},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment"},"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding"},"doc://mealz.MealziOSSDK/objc(cs)UINavigationController":{"type":"unresolvable","title":"UINavigationController","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"},"doc://mealz.MealziOSSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/mealz.MealziOSSDK\/SQ"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP"},"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://mealz.MealziOSSDK/SH":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://mealz.MealziOSSDK/s8SendableP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzOrderHistoryFeatureUIKit":{"title":"MealzOrderHistoryFeatureUIKit","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderHistoryFeatureUIKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}],"url":"\/documentation\/mealziossdk\/mealzorderhistoryfeatureuikit"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzOrderHistoryFeatureUIKit/init(hideTitles:recipeDetailsConstructor:orderHistoryFeatureConstructor:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzOrderHistoryFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:orderHistoryFeatureConstructor:)","url":"\/documentation\/mealziossdk\/mealzorderhistoryfeatureuikit\/init(hidetitles:recipedetailsconstructor:orderhistoryfeatureconstructor:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"hideTitles","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"text":", ","kind":"text"},{"text":"orderHistoryFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK30OrderHistoryFeatureConstructorV","text":"OrderHistoryFeatureConstructor"},{"text":")","kind":"text"}],"title":"init(hideTitles:recipeDetailsConstructor:orderHistoryFeatureConstructor:)","abstract":[]},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MealzOrderHistoryFeatureUIKit"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}]},{"value":[{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzOrderHistoryFeatureUIKit"},{"kind":"text","text":" : "},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderHistoryFeatureUIKit\/title","value":"MealzOrderHistoryFeatureUIKit","op":"replace"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderHistoryFeatureUIKit\/fragments","value":[{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MealzOrderHistoryFeatureUIKit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzOrderHistoryFeatureUIKit\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}