{"metadata":{"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"iPadOS"},{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst"}],"externalID":"c:@M@MealziOSSDK@objc(cs)MealzCatalogFeatureUIKit","roleHeading":"Class","title":"MealzCatalogFeatureUIKit","role":"symbol","modules":[{"name":"MealziOSSDK"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzCatalogFeatureUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"MealzCatalogFeatureUIKit"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzcatalogfeatureuikit"]},{"paths":["\/documentation\/mealziossdk\/mealzcatalogfeatureuikit"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/s8SendableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mySpaceConstructor:catalogFeatureConstructor:myMealsViewOptions:myMealsRecipesListGridConfig:mealPlannerFeatureConstructor:navigateToClientBasket:)"],"anchor":"Initializers","generated":true},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit\/openCatalogResults(catalogId:categoryTitle:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzCatalogFeatureUIKit"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring"},"doc://mealz.MealziOSSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s8SendableP"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject"},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP"},"doc://mealz.MealziOSSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/SQ"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP"},"doc://mealz.MealziOSSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/SH"},"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzCatalogFeatureUIKit/init(hideTitles:recipeDetailsConstructor:mySpaceConstructor:catalogFeatureConstructor:myMealsViewOptions:myMealsRecipesListGridConfig:mealPlannerFeatureConstructor:navigateToClientBasket:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mySpaceConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MySpaceFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK25MySpaceFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"catalogFeatureConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK25CatalogFeatureConstructorV","text":"CatalogFeatureConstructor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"myMealsViewOptions"},{"text":": ","kind":"text"},{"text":"MyMealsViewOptions","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK18MyMealsViewOptionsV"},{"text":", ","kind":"text"},{"text":"myMealsRecipesListGridConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK28CatalogRecipesListGridConfigV","text":"CatalogRecipesListGridConfig"},{"kind":"text","text":", "},{"text":"mealPlannerFeatureConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK29MealPlannerFeatureConstructorV","text":"MealPlannerFeatureConstructor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"navigateToClientBasket"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:mySpaceConstructor:catalogFeatureConstructor:myMealsViewOptions:myMealsRecipesListGridConfig:mealPlannerFeatureConstructor:navigateToClientBasket:)","role":"symbol","abstract":[],"title":"init(hideTitles:recipeDetailsConstructor:mySpaceConstructor:catalogFeatureConstructor:myMealsViewOptions:myMealsRecipesListGridConfig:mealPlannerFeatureConstructor:navigateToClientBasket:)","url":"\/documentation\/mealziossdk\/mealzcatalogfeatureuikit\/init(hidetitles:recipedetailsconstructor:myspaceconstructor:catalogfeatureconstructor:mymealsviewoptions:mymealsrecipeslistgridconfig:mealplannerfeatureconstructor:navigatetoclientbasket:)","kind":"symbol","type":"topic"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzCatalogFeatureUIKit/openCatalogResults(catalogId:categoryTitle:)":{"abstract":[],"url":"\/documentation\/mealziossdk\/mealzcatalogfeatureuikit\/opencatalogresults(catalogid:categorytitle:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openCatalogResults"},{"text":"(","kind":"text"},{"text":"catalogId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"categoryTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit\/openCatalogResults(catalogId:categoryTitle:)","kind":"symbol","title":"openCatalogResults(catalogId:categoryTitle:)"},"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment"},"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding"},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"},"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzCatalogFeatureUIKit":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzCatalogFeatureUIKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzCatalogFeatureUIKit"}],"role":"symbol","navigatorTitle":[{"text":"MealzCatalogFeatureUIKit","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mealziossdk\/mealzcatalogfeatureuikit","kind":"symbol","title":"MealzCatalogFeatureUIKit","type":"topic"},"doc://mealz.MealziOSSDK/objc(cs)UINavigationController":{"title":"UINavigationController","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"14.0"},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"14.0","unavailable":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"deprecated":false,"beta":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"MealzCatalogFeatureUIKit","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MealzCatalogFeatureUIKit","kind":"identifier"}]},{"value":[{"text":"MealzCatalogFeatureUIKit","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MealzCatalogFeatureUIKit"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzCatalogFeatureUIKit\/title","value":"MealzCatalogFeatureUIKit"},{"op":"replace","value":[{"text":"MealzCatalogFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzCatalogFeatureUIKit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzCatalogFeatureUIKit\/navigatorTitle","value":[{"kind":"identifier","text":"MealzCatalogFeatureUIKit"}]}]}]}