{"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/s8SendableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzrecipedetailsfeatureuikit"]},{"paths":["\/documentation\/mealziossdk\/mealzrecipedetailsfeatureuikit"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MealzRecipeDetailsFeatureUIKit","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeDetailsFeatureUIKit"},"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeDetailsFeatureUIKit\/init(recipeId:isMealzRecipe:hideTitles:recipeOpenedFrom:recipeDetailsConstructor:)"]}],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"MealzRecipeDetailsFeatureUIKit"}],"modules":[{"name":"MealziOSSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MealzRecipeDetailsFeatureUIKit","kind":"identifier"}],"role":"symbol","platforms":[{"introducedAt":"14.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"beta":false}],"symbolKind":"class","title":"MealzRecipeDetailsFeatureUIKit","externalID":"c:@M@MealziOSSDK@objc(cs)MealzRecipeDetailsFeatureUIKit"},"references":{"doc://mealz.MealziOSSDK/SQ":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeDetailsFeatureUIKit/init(recipeId:isMealzRecipe:hideTitles:recipeOpenedFrom:recipeDetailsConstructor:)":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeDetailsFeatureUIKit\/init(recipeId:isMealzRecipe:hideTitles:recipeOpenedFrom:recipeDetailsConstructor:)","url":"\/documentation\/mealziossdk\/mealzrecipedetailsfeatureuikit\/init(recipeid:ismealzrecipe:hidetitles:recipeopenedfrom:recipedetailsconstructor:)","title":"init(recipeId:isMealzRecipe:hideTitles:recipeOpenedFrom:recipeDetailsConstructor:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recipeId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"isMealzRecipe","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeOpenedFrom"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MealzcoreMealzPage","kind":"typeIdentifier","text":"MealzPage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[]},"doc://mealz.MealziOSSDK/s8SendableP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(cs)UINavigationController":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController","title":"UINavigationController","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeDetailsFeatureUIKit":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MealzRecipeDetailsFeatureUIKit","kind":"identifier"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeDetailsFeatureUIKit","title":"MealzRecipeDetailsFeatureUIKit","role":"symbol","type":"topic","url":"\/documentation\/mealziossdk\/mealzrecipedetailsfeatureuikit","navigatorTitle":[{"kind":"identifier","text":"MealzRecipeDetailsFeatureUIKit"}],"abstract":[],"kind":"symbol"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://mealz.MealziOSSDK/SH":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iOS","beta":false},{"introducedAt":"14.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MealzRecipeDetailsFeatureUIKit"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MealzRecipeDetailsFeatureUIKit","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MealzRecipeDetailsFeatureUIKit"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UINavigationController"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"MealzRecipeDetailsFeatureUIKit","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeDetailsFeatureUIKit\/title","value":"MealzRecipeDetailsFeatureUIKit","op":"replace"},{"op":"replace","value":[{"text":"MealzRecipeDetailsFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeDetailsFeatureUIKit\/fragments"},{"op":"replace","value":[{"text":"MealzRecipeDetailsFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeDetailsFeatureUIKit\/navigatorTitle"}]}]}