{"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UIViewController"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/s8SendableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring"]}],"metadata":{"externalID":"c:@M@MealziOSSDK@objc(cs)MealzBasketTagFeatureUIKit","roleHeading":"Class","role":"symbol","modules":[{"name":"MealziOSSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"}],"platforms":[{"deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"14.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"beta":false}],"title":"MealzBasketTagFeatureUIKit","navigatorTitle":[{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"}],"symbolKind":"class"},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit\/init(retailerProductId:scrollAlignment:recipeDetailsConstructor:basketTagFeatureConstructor:)"],"anchor":"Initializers"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit\/viewDidLoad()"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit"]}],"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIStateRestoring","type":"unresolvable"},"doc://mealz.MealziOSSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/mealz.MealziOSSDK\/s8SendableP","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://mealz.MealziOSSDK/SH":{"identifier":"doc:\/\/mealz.MealziOSSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(cs)UIViewController":{"title":"UIViewController","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)UIViewController","type":"unresolvable"},"doc://mealz.MealziOSSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/mealz.MealziOSSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzBasketTagFeatureUIKit/viewDidLoad()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit\/viewDidLoad()","url":"\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit\/viewdidload()","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"role":"symbol","title":"viewDidLoad()","abstract":[],"type":"topic"},"doc://mealz.MealziOSSDK/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSExtensionRequestHandling","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzBasketTagFeatureUIKit":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit","type":"topic","navigatorTitle":[{"text":"MealzBasketTagFeatureUIKit","kind":"identifier"}],"url":"\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"}],"title":"MealzBasketTagFeatureUIKit"},"doc://mealz.MealziOSSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/mealz.MealziOSSDK\/SQ","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzBasketTagFeatureUIKit/init(retailerProductId:scrollAlignment:recipeDetailsConstructor:basketTagFeatureConstructor:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"retailerProductId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"scrollAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Axis","preciseIdentifier":"s:7SwiftUI4AxisO","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4AxisO3SetV","text":"Set"},{"kind":"text","text":", "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"kind":"text","text":", "},{"text":"basketTagFeatureConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BasketTagFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK27BasketTagFeatureConstructorV"},{"kind":"text","text":")"}],"title":"init(retailerProductId:scrollAlignment:recipeDetailsConstructor:basketTagFeatureConstructor:)","kind":"symbol","type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit\/init(retailerProductId:scrollAlignment:recipeDetailsConstructor:basketTagFeatureConstructor:)","url":"\/documentation\/mealziossdk\/mealzbaskettagfeatureuikit\/init(retailerproductid:scrollalignment:recipedetailsconstructor:baskettagfeatureconstructor:)","role":"symbol","abstract":[]},"doc://mealz.MealziOSSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iOS"},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"14.0","beta":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"14.0","unavailable":false,"deprecated":false}],"op":"replace","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MealzBasketTagFeatureUIKit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzBasketTagFeatureUIKit\/viewDidLoad()"],"anchor":"Instance-Methods"}]},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)UIViewController"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit~1viewDidLoad()\/title"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MealzBasketTagFeatureUIKit","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MealzBasketTagFeatureUIKit"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit\/fragments"},{"op":"replace","value":[{"text":"MealzBasketTagFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzBasketTagFeatureUIKit\/navigatorTitle"}]}]}