{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzrecipedetailsfeatureuikit\/init(recipeid:ismealzrecipe:hidetitles:recipeopenedfrom:recipedetailsconstructor:)"]}],"sections":[],"metadata":{"symbolKind":"init","role":"symbol","modules":[{"name":"MealziOSSDK"}],"platforms":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"14.0"},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"14.0","beta":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false}],"externalID":"s:11MealziOSSDK30MealzRecipeDetailsFeatureUIKitC8recipeId02iscD010hideTitles0H10OpenedFrom0hE11ConstructorACSS_S2bSo09MealzcoreC4PageCAA0defO0Vtcfc","roleHeading":"Initializer","title":"init(recipeId:isMealzRecipe:hideTitles:recipeOpenedFrom:recipeDetailsConstructor:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"recipeId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isMealzRecipe","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideTitles"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"recipeOpenedFrom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MealzPage","preciseIdentifier":"c:objc(cs)MealzcoreMealzPage"},{"kind":"text","text":", "},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"recipeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"isMealzRecipe","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"recipeOpenedFrom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MealzcoreMealzPage","text":"MealzPage","kind":"typeIdentifier"},{"kind":"text","text":" = .catalog, "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV"},{"kind":"text","text":" = RecipeDetailsFeatureConstructor())"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeDetailsFeatureUIKit\/init(recipeId:isMealzRecipe:hideTitles:recipeOpenedFrom:recipeDetailsConstructor:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeDetailsFeatureUIKit"]]},"kind":"symbol","references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeDetailsFeatureUIKit/init(recipeId:isMealzRecipe:hideTitles:recipeOpenedFrom:recipeDetailsConstructor:)":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeDetailsFeatureUIKit\/init(recipeId:isMealzRecipe:hideTitles:recipeOpenedFrom:recipeDetailsConstructor:)","url":"\/documentation\/mealziossdk\/mealzrecipedetailsfeatureuikit\/init(recipeid:ismealzrecipe:hidetitles:recipeopenedfrom:recipedetailsconstructor:)","title":"init(recipeId:isMealzRecipe:hideTitles:recipeOpenedFrom:recipeDetailsConstructor:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recipeId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"isMealzRecipe","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipeOpenedFrom"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MealzcoreMealzPage","kind":"typeIdentifier","text":"MealzPage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzRecipeDetailsFeatureUIKit":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MealzRecipeDetailsFeatureUIKit","kind":"identifier"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzRecipeDetailsFeatureUIKit","title":"MealzRecipeDetailsFeatureUIKit","role":"symbol","type":"topic","url":"\/documentation\/mealziossdk\/mealzrecipedetailsfeatureuikit","navigatorTitle":[{"kind":"identifier","text":"MealzRecipeDetailsFeatureUIKit"}],"abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MealzRecipeDetailsFeatureUIKit","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeDetailsFeatureUIKit\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeDetailsFeatureUIKit\/fragments","value":[{"text":"MealzRecipeDetailsFeatureUIKit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzRecipeDetailsFeatureUIKit\/navigatorTitle","value":[{"kind":"identifier","text":"MealzRecipeDetailsFeatureUIKit"}],"op":"replace"}]}]}