{"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyBasketFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:myBasketContructor:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","modules":[{"name":"MealziOSSDK"}],"externalID":"s:11MealziOSSDK25MealzMyBasketFeatureUIKitC10hideTitles24recipeDetailsConstructor02myE10ContructorACSb_AA06RecipekfL0VAA0defL0Vtcfc","platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"14.0"},{"beta":false,"introducedAt":"14.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"14.0"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","text":"RecipeDetailsFeatureConstructor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"myBasketContructor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK26MyBasketFeatureConstructorV","kind":"typeIdentifier","text":"MyBasketFeatureConstructor"},{"text":")","kind":"text"}],"title":"init(hideTitles:recipeDetailsConstructor:myBasketContructor:)","role":"symbol","roleHeading":"Initializer"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/mealzmybasketfeatureuikit\/init(hidetitles:recipedetailsconstructor:mybasketcontructor:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyBasketFeatureUIKit"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"recipeDetailsConstructor"},{"kind":"text","text":": "},{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","text":"RecipeDetailsFeatureConstructor","preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier"},{"kind":"text","text":" = RecipeDetailsFeatureConstructor(), "},{"kind":"externalParam","text":"myBasketContructor"},{"kind":"text","text":": "},{"text":"MyBasketFeatureConstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MyBasketFeatureConstructor","kind":"typeIdentifier","preciseIdentifier":"s:11MealziOSSDK26MyBasketFeatureConstructorV"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/RecipeDetailsFeatureConstructor":{"navigatorTitle":[{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"RecipeDetailsFeatureConstructor","role":"symbol","url":"\/documentation\/mealziossdk\/recipedetailsfeatureconstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/RecipeDetailsFeatureConstructor","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RecipeDetailsFeatureConstructor","kind":"identifier"}]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MyBasketFeatureConstructor":{"role":"symbol","title":"MyBasketFeatureConstructor","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MyBasketFeatureConstructor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyBasketFeatureConstructor","kind":"identifier"}],"navigatorTitle":[{"text":"MyBasketFeatureConstructor","kind":"identifier"}],"type":"topic","url":"\/documentation\/mealziossdk\/mybasketfeatureconstructor","abstract":[],"kind":"symbol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMyBasketFeatureUIKit/init(hideTitles:recipeDetailsConstructor:myBasketContructor:)":{"type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyBasketFeatureUIKit\/init(hideTitles:recipeDetailsConstructor:myBasketContructor:)","title":"init(hideTitles:recipeDetailsConstructor:myBasketContructor:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hideTitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"recipeDetailsConstructor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MealziOSSDK31RecipeDetailsFeatureConstructorV","kind":"typeIdentifier","text":"RecipeDetailsFeatureConstructor"},{"text":", ","kind":"text"},{"text":"myBasketContructor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11MealziOSSDK26MyBasketFeatureConstructorV","kind":"typeIdentifier","text":"MyBasketFeatureConstructor"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/mealziossdk\/mealzmybasketfeatureuikit\/init(hidetitles:recipedetailsconstructor:mybasketcontructor:)"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/MealzMyBasketFeatureUIKit":{"url":"\/documentation\/mealziossdk\/mealzmybasketfeatureuikit","type":"topic","title":"MealzMyBasketFeatureUIKit","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/MealzMyBasketFeatureUIKit","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MealzMyBasketFeatureUIKit","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MealzMyBasketFeatureUIKit"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"MealzMyBasketFeatureUIKit","op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyBasketFeatureUIKit\/title"},{"op":"replace","value":[{"text":"MealzMyBasketFeatureUIKit","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyBasketFeatureUIKit\/fragments"},{"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1MealzMyBasketFeatureUIKit\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MealzMyBasketFeatureUIKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}